services:
  - type: web
    name: reserhub-commerce-api
    env: docker
    plan: free
    healthCheckPath: /hello/World
    envVars:
      - key: NODE_ENV
        value: production
    buildFilter:
      paths:
        - apps/commerce-api/**/*
