name: Commerce API Type Check

on:
  pull_request:
    paths:
      - "apps/commerce-api/**"

jobs:
  type-check:
    name: Generate client and check types
    runs-on: ubuntu-latest
    steps:
      - name: Fetching repository code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ">=18"
          cache: "npm"

      - name: Download Encore CLI script
        uses: sozo-design/curl@v1.0.2
        with:
          args: --output install.sh -L https://encore.dev/install.sh

      - name: Install Encore CLI
        run: |
          bash install.sh
          echo "$HOME/.encore/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: npm ci

      - name: Encore Check
        run: npm run encore:check

      - name: Generate Encore API client
        run: npm run encore:gen-client

      - name: Check types
        run: npm run check-types
